### PR TITLE
Fixes for Upgrade Wall / Request CC

### PR DESCRIPTION
**Pull request by cmestres**
https://gamebot.org/forums/showthread.php?tid=1717

### CODE REVIEW

**Comment by promac2k** [comment]
cmestres , boa noite ... podemos falar por outro meio ? sou o ProMac do CGB

**Comment by cmestres** [comment]
Claro! Manda inbox ai pelo forum!

**Comment by promac2k** [comment]
Estamos a passar a outro servidor ... já mando uma PM ;) como é bom escrever Portugues jejjejejej
depois mando o meu skype ...

**Comment by Blaze5145** [comment]
Umm guys English please :p

**Comment by Heeere-GittyGitty** [comment]
Olá Tuga está um tempo da caca aqui por Lisboa :)
(aka: Hello Good People) :)

Please include me in the loop also! I've tried to submit a quick workaround i did for this but I don't know how to make a pull request.
Take a look at the issue I created, in the "issues" thread:
https://github.com/Blaze5145/cgb-unofficial/issues/29

I'd be glad to help.

**Pull request merged**
