### PR TITLE
remove include of algorithm_Barch.au3 and new russian symbols and digits recongition

### PR DESCRIPTION
**Pull request by krendll**
no need to include the file as it is not used in the future, possibly the file itself also need to remove

functions\Attack\Attack Algorithms\algorithm_Barch.au3

### CODE REVIEW

**Comment by Blaze5145** [comment]
You sure about it? We can just leave it there. It's doing no harm :P

**Comment by krendll** [comment]
Autoit get's in error during run with it because of error in algorithm_Barch.au3. It's only for clean code, nothing more.
Consolelog:

"\COCBot\functions\Attack\Attack Algorithms\algorithm_Barch.au3"(23,25) : warning: $deploySettings: possibly used before declaration.
        Switch $deploySettings
        ~~~~~~~~~~~~~~~~~~~~~~^
"COCBot\functions\Attack\Attack Algorithms\algorithm_Barch.au3"(23,25) : error: $deploySettings: undeclared global variable.
        Switch $deploySettings

**Comment by Blaze5145** [comment]
So are the functions in that file still used?

**Comment by krendll** [comment]
Nope. File contains only one function "Func Barch()", which is never used in all script.

**Comment by Blaze5145** [comment]
Alright. Make changes to the latest master because if I merge your code now, the GPL header will be lost... so please sync your master with mine and then create a pull request

**Comment by krendll** [comment]
I am new to git, so i made new pull request. This one should be deleted.

**Pull request closed without merging**
